---
title: "Heavy Tailed Distribution"
author: "Peiran Zhang"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(car)
library(RNOmni)
library(VGAM)
library(GeneralizedHyperbolic)
library(lsr)
library(lmPerm)
library(pwr)
library(coin)
library(Deducer)

INT_function = function(x, n, k) { 
  output = 0
  ranks = rank(x)
  for (i in 1:n) {
    output[i] = probitlink((ranks[i] - k)/(n + 1 - 2*k))
  }
  return(output)
}
```


## More Heavy Tailed Distributions

## Cauchy Distribution
```{r}
# n = 20

x = density(rcauchy(20, 0, 2))
plot(x)

simulation = 1000 
k = 0.4
n = 20
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA

for(i in 1 : simulation){
  original = rcauchy(n, 0, 2)
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 20")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 20")
```

```{r}
# n = 50

x = density(rcauchy(50, 0, 2))
plot(x)

simulation = 1000 
k = 0.4
n = 50
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA

for(i in 1 : simulation){
  original = rcauchy(n, 0, 2)
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 50")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 50")
```

```{r}
# n = 100

x = density(rcauchy(100, 0, 2))
plot(x)

simulation = 1000 
k = 0.4
n = 100
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA

for(i in 1 : simulation){
  original = rcauchy(n, 0, 2)
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 100")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 100")
```

## Log-Cauchy Distribution
```{r}
# n = 20

rlogcauchy = function(n, mu, sigma) {
    u = runif(n)
    x = mu + sigma * tan(pi * (u - 0.5))
    return(exp(x)) 
}

x = density(rlogcauchy(20, 0, 0.1))
plot(x)

simulation = 1000 
k = 0.4
n = 20
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA

for(i in 1 : simulation) {
  original = rlogcauchy(n, 0, 0.1)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 20")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 20")
```

```{r}
# n = 50

rlogcauchy = function(n, mu, sigma) {
    u = runif(n)
    x = mu + sigma * tan(pi * (u - 0.5))
    return(exp(x)) 
}

x = density(rlogcauchy(50, 0, 0.1))
plot(x)

simulation = 1000 
k = 0.4
n = 50
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA

for(i in 1 : simulation) {
  original = rlogcauchy(n, 0, 0.1)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 50")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 50")
```

```{r}
# n = 100

rlogcauchy = function(n, mu, sigma) {
    u = runif(n)
    x = mu + sigma * tan(pi * (u - 0.5))
    return(exp(x)) 
}

x = density(rlogcauchy(100, 0, 0.1))
plot(x)

simulation = 1000 
k = 0.4
n = 100
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA



for(i in 1 : simulation) {
  original = rlogcauchy(n, 0, 0.1)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 100")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 100")
```

## Log Normal Distribution
```{r}
# set the standard deviation of the distribution on the log scale to 1
plot(density(rlnorm(n, meanlog = 0, sdlog = 1)))
```

```{r}
simulation = 1000 
k = 0.4
n = 100
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA



for(i in 1 : simulation) {
  original = rlnorm(n, meanlog = 0, sdlog = 1)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 100")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 100")
```

```{r}
# change the standard deviation of the distribution on the log scale to 2
plot(density(rlnorm(n, meanlog = 0, sdlog = 2)))
```

```{r}
simulation = 1000 
k = 0.4
n = 100
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA



for(i in 1 : simulation) {
  original = rlnorm(n, meanlog = 0, sdlog = 2)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 100")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 100")
```

```{r}
# change the standard deviation of the distribution on the log scale to 3
plot(density(rlnorm(n, meanlog = 0, sdlog = 3)))
```

```{r}
simulation = 1000 
k = 0.4
n = 100
X1 = c(rep(1, n/2), rep(0, n/2))
X2 = c(rep(0, n/2), rep(1, n/2))
A = matrix(c(X1, X2), nrow = n, ncol=2) 
p_original = vector(length = simulation)
error_original_005 = NA
error_original_001 = NA
error_original_0001 = NA
p_transformed = vector(length = simulation)
error_transformed_005 = NA
error_transformed_001 = NA
error_transformed_0001 = NA



for(i in 1 : simulation) {
  original = rlnorm(n, meanlog = 0, sdlog = 3)
  original[is.na(original) | original == "Inf"] = NA
  fit_original = lm(formula = original ~ A) 
  p_original[i] = summary(fit_original)$coefficients[2,4]
  if (p_original[i] < 0.05) {
    error_original_005[i] = 1
  }
  if (p_original[i] < 0.01) {
    error_original_001[i] = 1
  }
  if (p_original[i] < 0.001) {
    error_original_0001[i] = 1
  }
  transformed = INT_function(original, n, k)
  fit_transformed = lm(formula = transformed ~ A)
  p_transformed[i] = summary(fit_transformed)$coefficients[2,4]
  if (p_transformed[i] < 0.05) {
    error_transformed_005[i] = 1
  }
  if (p_transformed[i] < 0.01) {
    error_transformed_001[i] = 1
  }
  if (p_transformed[i] < 0.001) {
    error_transformed_0001[i] = 1
  }
}
table(error_original_005)
table(error_original_001)
table(error_original_0001)
table(error_transformed_005)
table(error_transformed_001)
table(error_transformed_0001)
hist(p_original, main = "Distribution of p-values for Original Data with Sample Size 100")
hist(p_transformed, main = "Distribution of p-values for Transformed Data with Sample Size 100")
```



