---
title: "Project"
author: "Peiran Zhang"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(car)
library(RNOmni)
library(VGAM)
```



## Power Transformation
## Normal Distribution
```{r}
set.seed(1000)
n = 1000
original = rnorm(n)
original = original + abs(min(original)) + 0.01 # make the set all positive for Box-Cox

b = powerTransform(original) # using powerTransform function
transformed = bcPower(original, b$lambda)
par(mfrow=c(1,2))
hist(original)
hist(transformed)
```
## T Distribution
```{r}
set.seed(1000)
n = 1000
original = rt(n, df = 10)
original = original + abs(min(original)) + 0.01
b = powerTransform(original)
transformed = bcPower(original, b$lambda)
par(mfrow=c(1,2))
hist(original)
hist(transformed)
```
## Exponential Distribution
```{r}
set.seed(1000)
n = 1000
original = rexp(n)
b = powerTransform(original)
transformed = bcPower(original, b$lambda)
par(mfrow=c(1,2))
hist(original)
hist(transformed)
```
## Chi-square Distribution
```{r}
set.seed(1000)
n = 1000
original = rchisq(n, df = 1)
b = powerTransform(original)
transformed = bcPower(original, b$lambda)
par(mfrow=c(1,2))
hist(original)
hist(transformed)
```



## Inverse Normal Transformation
## Function
```{r}
## r = ranks; n = number of subjects; c = offset; output= vector of transformed data
INT_function = function(x, n, k) { 
  output = 0
  ranks = rank(x)
  for (i in 1:n) {
    output[i] = probitlink((ranks[i] - k)/(n + 1 - 2*k))
  }
  return(output)
}
```
## Normal Distribution
```{r}
set.seed(1000)
n = 1000
original = rnorm(n)
k = 1/10
after_trans = INT_function(original, n, k) 
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 3/8
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 6/7
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 9/10
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 200/347
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
## T Distribution
```{r}
set.seed(1000)
n = 1000
original = rt(n, df = 10)
k = 0
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 0.3
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 0.79
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
## Exponential Distribution
```{r}
set.seed(1000)
n = 1000
original = rexp(n)
k = 0
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 0.8
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 1.2
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
## Chi-squre Distribution
```{r}
set.seed(1000)
n = 1000
original = rchisq(n, df = 1)
k = 0
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 0.5
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```
```{r}
k = 1
after_trans = INT_function(original, n, k)
par(mfrow=c(1,2))
hist(original)
hist(after_trans)
```



## R Package
```{r}
install.packages("/Users/peggyzhang/Desktop/MATH/Project/INT_0.0.0.9000.tar.gz", repos = NULL, type = "source")
library(INT)
set.seed(1000) ## test
n = 1000
original = rnorm(n)
k = 0
INT_function(original, n, k)
```

